### ISSUE TITLE
[Feature Request] How to use cli command?

### ISSUE THREAD

**Issue by ucxl** [mywalkb/LSPosed_mod#1]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

How to use cli command? 

### Describe the solution you'd like/描述你想要的解决方案

How to use cli command? Are there any examples? thank you!

**Comment by mywalkb** [comment]
Sorry for the delay.
I will make a wiki page.
If you run /data/adb/lspd/bin/cli from root user there is a partial help.

There are 4 subcommand
- log (print LSPosed log)
- modules (manage modules, enable/disable and list)
- scope (manage scope for module)
- status (status of LSPosed)

In the last build there is an issue, I will try to fix it.

**Comment by mywalkb** [comment]
[Here](https://github.com/mywalkb/LSPosed_mod/wiki/CLI) you can find a wiki, I hope is good, otherwise I will try to improve it

**Comment by ucxl** [comment]
Thank you very much. I'd like to make some suggestions, because users choose root and lsposed. They don't care about some security issues. Therefore, there is no need to enable the CLI switch or verify the pin. On the contrary, it increases the difficulty of operation. The module author knows the module scope, but the user does not know it. Therefore, we hope to set the module scope at the same time when setting the module function through the shell. Switch and pin certification are not required. CLI has some garbled code in the ADB shell interface, so it is unable to get the correct help

**Comment by mywalkb** [comment]
> They don't care about some security issues. Therefore, there is no need to enable the CLI switch or verify the pin.

It's a very long story. The CLI patch is not mine, I got it from a user who tried to create a PR. The LSPosed mainteiner required a lot of changes and although all of them were satisfied, the PR was not merged. PIN, switch, session timeout, these are all mainteiner requests that I have kept for convenience, maybe a day I will remove them.

> The module author knows the module scope, but the user does not know it.

The user can do `cli scope ls <module name>` and know it.

> Therefore, we hope to set the module scope at the same time when setting the module function through the shell.

Ok I will try to improve it

> CLI has some garbled code in the ADB shell interface

I think this is due to the fact that there are colors in the shell and if your terminal doesn't handle them properly it creates some weird characters
![Screenshot](https://user-images.githubusercontent.com/66966897/169639494-4301d48a-eee6-48df-adbd-746687e280f4.png)
