### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by jb82gm** [mywalkb/LSPosed_mod#16]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I see Enabling Zygisk for using LSposed is causing problems. I'm on KernelSU and most apps work fine for me but whenever I enable Zygisk to Install LSPosed, Many apps start detecting root.

### Describe the solution you'd like/描述你想要的解决方案

Is it possible to make LSposed that works without Zygisk or Riru or making a Lsposed version for KernelSU that doesn't relies on Zygisk at all.

I'll be more then happy to beta test it If you care about making it :)

**Comment by mywalkb** [comment]
LSPosed can't work without Zygisk or Riru, because they inject LSPosed into processes for hooks.
For a version which use KernelSU is out of my scope, I don't have the skills to do it.
There is already an [issue](https://github.com/LSPosed/LSPosed/issues/2359) on main LSPosed, which report

> Its API is not yet stable.

You can try to update that issue, for understand which is the situation.
If LSPosed will support KernelSU also LSPosed_mod will support it.

**Comment by mywalkb** [comment]
Have you tried [this](https://github.com/Dr-TSNG/ZygiskOnKernelSU) ?
Run zygisk modules on kernelsu without magisk, maybe works with LSPosed/LSPosed_mod

**Comment by mywalkb** [comment]
it seems possible by watching this [video](https://www.youtube.com/watch?v=XX5XgdlAS8E)

**Comment by jb82gm** [comment]
I've tried this. kernelSU has hidden root method (By Default) and 99% apps wont detect it at all. The moment you Install Zygisk on KSU, The hidden root looses itself and apps start detecting the root or change in environment. 

This is the reason, I asked you to check if you can make a LSposed mod that works on SU permission. Since KSU gives root on Kernel basis and possibilities are endless. LSposed for KSU direct without Zygisk will be ground breaking IMO.
