### ISSUE TITLE
LSPosed_mod7279The log is not working

### ISSUE THREAD

**Issue by mJtUyT** [mywalkb/LSPosed_mod#80]
### Steps to reproduce

Normal brush-in 7279

### Expected behaviour

There should be logging reports. If this is a new feature, please provide a logging switch.

### Actual behaviour

The log is not working properly
![Screenshot_2024-04-20-15-32-29-36_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/mywalkb/LSPosed_mod/assets/132890073/3fd458db-8c94-4e74-ada6-d93afd506af8)
![Screenshot_2024-04-20-15-31-56-54_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/mywalkb/LSPosed_mod/assets/132890073/e0fe2203-9567-4671-b6f5-8ab7dc08504f)

### Xposed Module List

```shell
LuckyTool、Thanox、Scene、逗音小能手、NoActive、微x模块、哔哩会员画质、隐藏应用列表 ……，This probably has nothing to do with the module list, I just updated LSPosed _ mod
```

### Magisk Module List

```shell
I only updated LSPosed _ mod.
```

### LSPosed version

7279

### Android version

Android14

### Magisk version

KernelSU 11795

### Riru version

zygisk

### Version requirement

- [X] I am using latest debug CI version of LSPosed and enable verbose log

### Logs

[LSPosed_2024-04-20T15_32_36.241169.zip](https://github.com/mywalkb/LSPosed_mod/files/15047313/LSPosed_2024-04-20T15_32_36.241169.zip)

**Comment by mywalkb** [comment]
Could you tell me how you arrived at that build?
Only main branch should appears as canary build.
That build is in testnologs branch, so is only a test and shouldn't appear anywhere.

**Comment by mJtUyT** [comment]
> 你能告诉我你是怎么得到这个版本的吗？只有 main 分支应显示为 Canary build。该版本位于 testnologs 分支中，因此只是一个测试，不应出现在任何地方。

In Action out of the download, if 7279 is not correct, I will go back to 7278

**Comment by mywalkb** [comment]
You should use the links in section [Download](https://github.com/mywalkb/LSPosed_mod?tab=readme-ov-file#download) of README or [this](https://github.com/mywalkb/LSPosed_mod/actions/workflows/core.yml?query=branch%3Amain) link which filter for main branch, so you avoid installing test builds that bring no benefits, unless you want to try some app that detects LSPosed through logs.
That build is a test that is used to remove the logs as requested in feature request #76.
Yes go back to 7278, because 7279 is just a test and will never release in official build with this behavior.
